TWILIO_ACCOUNT_SID = "YOUR_TWILIO_ACCOUNT_SID"
TWILIO_AUTH_TOKEN = "YOUR_TWILIO_AUTH_TOKEN"
TWILIO_FROM_NUMBER = "YOUR_TWILIO_FROM_NUMBER"  # your Twilio number
EMERGENCY_CONTACT = "YOUR_EMERGENCY_CONTACT"  # or your local emergency number
GROQ_API_KEY = "YOUR_GROQ_API_KEY"   # Free
# OPENAI_API_KEY=""     # Paid
GOOGLE_MAPS_API_KEY = "YOUR_GOOGLE_MAPS_API_KEY"  # Free